-- 1. Create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    text TEXT NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 3. Drop any existing conflicting policies to ensure a clean slate
DROP POLICY IF EXISTS "Public can view approved reviews" ON public.reviews;
DROP POLICY IF EXISTS "Public can insert reviews" ON public.reviews;
DROP POLICY IF EXISTS "Anyone can insert reviews" ON public.reviews;

-- 4. Create secure RLS Policies

-- PUBLIC SELECT: Anyone can view reviews, but ONLY if they are approved
CREATE POLICY "Public can view approved reviews" 
ON public.reviews 
FOR SELECT 
USING (approved = true);

-- PUBLIC INSERT: Anyone can insert a review, but they CANNOT force approved = true
-- This securely prevents a malicious user from auto-approving their own review.
CREATE POLICY "Public can insert reviews" 
ON public.reviews 
FOR INSERT 
WITH CHECK (approved = false);

-- No UPDATE or DELETE policies are granted to the 'anon' or 'public' role.
-- Public users are completely blocked from modifying approval status or deleting reviews.
-- Admin actions (approve, delete) use the SUPABASE_SERVICE_ROLE_KEY on the server, which safely bypasses RLS entirely.
